# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - BritEdgeJobSchedulerApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://britedgeregistry-h5amf4e9cndugrbq.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4b5deff2c83b404cb93b38beec4bf060 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_741b848a35c24d159307284817a9110f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: britedgeregistry-h5amf4e9cndugrbq.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4b5deff2c83b404cb93b38beec4bf060 }}/graceleeada1888/briteedgeapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BritEdgeJobSchedulerApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7d28d96d545345778312398e85ae95aa }}
        images: 'britedgeregistry-h5amf4e9cndugrbq.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4b5deff2c83b404cb93b38beec4bf060 }}/graceleeada1888/briteedgeapp:${{ github.sha }}'